baseurl: "https://antgubarev.dev"
theme: "antgubarev"

languageCode: "en-us"
defaultContentLanguage: "en"

params:
    author: "Anton Gubarev"
    info: "Software engineer"
    description: "Anton Gubarev's personal website about web software development"
    keywords: "губарев,gubarev,antgubarev,web,highload,хайлоад,goland,devops"
    customCSS:
        - "css/custom.css"