baseurl = "https://antgubarev.dev"
theme = "antgubarev"

languagecode = 'en'
defaultcontentlanguage = 'en'

paginate = 5
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "antgubarev"

[params]
    author = "Anton Gubarev"
    info = "Software engineer"
    description = "Anton Gubarev's personal website about web software development"
    keywords = "губарев,gubarev,antgubarev,web,highload,хайлоад,goland,devops"
    avatarurl = "images/photo.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true
    customCSS = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/antgubarev"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/antgubarev/"
[[params.social]]
    name = "Telegram"
    icon = "fa fa-telegram fa-2x"
    weight = 3
    url = "https://t.me/antgubarev"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/antgubarev/"