baseurl: "https://antgubarev.me"
theme: "antgubarev"

languageCode: "en-us"
defaultContentLanguage: "en"

params:
    author: "Anton Gubarev"
    info: "Software engineer"
    description: "Anton Gubarev's personal website"
    keywords: "губарев,gubarev,antgubarev,highload,техлидошная"
    customCSS:
        - "css/custom.css"
