en:
    title: "Anton Gubarev"
    languageName: "eng"
    weight: 1
    contentDir: "content/en"
    params:
        description: "Anton Gubarev's personal website about web software development"
        keywords: "gubarev,antgubarev,web,highload,goland,devops"

ru:
    languagedirection: "ru"
    title: "Anton Gubarev"
    languageName: "rus"
    weight: 2
    contentDir: "content/ru"
    params:
        description: "Персональный блог Антона Губарева о разработке"
        keywords: "губарев"