theme = "tech"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
defaultContentLanguage = "en"
baseURL = "https://antgubarev.tech"

[languages]

  [languages.en]
    title = 'Anton Gubarev'
	contentDir = "content/en"
    weight = 1

  [languages.en.menu]

	  [[languages.en.menu.main]]
		identifier = "cv"
		name = "CV"
		title = "cv"
		url = "https://drive.google.com/file/d/1O2KRaw0AKy5mDJxwVaWim1jpYyj9LeVo/view?usp=sharing"
		weight = 30
		[languages.en.menu.main.params]
			target = "_blank"

	  [[languages.en.menu.main]]
		 identifier = "ru"
		 name = "ru"
		 title = "ru"
		 url = "/ru/"
		 weight = 40

  [languages.ru]
   title = 'Антон Губарев'
	contentDir = "content/ru"
   weight = 2

  [languages.ru.menu]

	  [[languages.ru.menu.main]]
		identifier = "posts"
		name = "Статьи"
		title = "Статьи"
		url = "/ru/tags/post/"
		weight = 1

	  [[languages.ru.menu.main]]
		identifier = "webinars"
		name = "Вебинары"
		title = "Вебинары"
		url = "/ru/tags/webinar/"
		weight = 2

	  [[languages.ru.menu.main]]
		identifier = "talks"
		name = "Доклады"
		title = "Доклады"
		url = "/ru/tags/talk/"
		weight = 3

	  [[languages.ru.menu.main]]
		identifier = "about"
		name = "Обо мне"
		title = "Обо мне"
		url = "/ru/about/"
		weight = 4

	  [[languages.ru.menu.main]]
		identifier = "rss"
		name = "RSS"
		title = "RSS"
		url = "/ru/index.xml"
		weight = 30

	  [[languages.ru.menu.main]]
		 identifier = "en"
		 name = "en"
		 title = "en"
		 url = "/"
		 weight = 40

[params]
  description = "Anton Gubarev's personal website"
  copyright = "Copyright © 2024 Anton Gubarev"
  dark = "off"
  highlight = true
  ymCode = "92567493"

   [[params.social]]
		name = "GitHub"
		weight = 1
		url = "https://github.com/antgubarev"
		target="_blank"
	[[params.social]]
		name = "LinkedIn"
		weight = 2
		url = "https://www.linkedin.com/in/antgubarev/"
		target="_blank"

	[[params.social]]
		name = "GetMentor"
		weight = 3
		url = "https://getmentor.dev/mentor/anton-gubarev-2900"
		target="_blank"

	[[params.social]]
		name = "Техлидошная"
		weight = 3
		url = "https://t.me/devlead"
		target="_blank"

[permalinks]
  posts = "/:year/:month/:slug/"

[markup.goldmark.renderer]
  unsafe = true
