baseurl = "https://antgubarev.com"
title = "antgubarev"
theme = "hugo-coder"
languagecode = "ru"
defaultcontentlanguage = "ru"

paginate = 5
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "antgubarev"

[params]
    author = "Anton Gubarev"
    info = "Php/Go Developer and Team Leader"
    description = "Anton Gubarev's personal website"
    keywords = "blog,developer,personal,teamleader,php,golang"
    avatarurl = "images/photo.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/antgubarev"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/antgubarev/"
[[params.social]]
    name = "Vk"
    icon = "fab fa-vk fa-2x"
    weight = 3
    url = "https://twitter.com/antgubarev/"

# Menu links
[[menu.main]]
    name = "Обо мне"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Канал в телеге"
    weight = 3
    url = "https://t.me/antgubarevcom"