baseurl = "https://antgubarev.dev"
title = "antgubarev"
theme = "hugo-coder"
languagecode = "ru"
defaultcontentlanguage = "ru"

paginate = 5
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "antgubarev"

googleAnalytics = "UA-130625425-1"

[params]
    author = "Anton Gubarev"
    info = "Web architect and engineer"
    description = "Anton Gubarev's personal website"
    keywords = "губарев,gubarev,web,consulting,architecture,архитектура,highload,хайлоад"
    avatarurl = "images/photo.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/antgubarev"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/antgubarev/"
[[params.social]]
    name = "Vk"
    icon = "fab fa-vk fa-2x"
    weight = 3
    url = "https://vk.com/antgubarev/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/antgubarev/"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram fa-2x"
    weight = 3
    url = "https://t.me/antgubarev"

# Menu links
[[menu.main]]
    name = "Обо мне"
    weight = 1
    url = "/about/"
[[menu.main]]
     name = "Выступления"
     weight = 2
     url = "/talks/"
[[menu.main]]
    name = "Канал в телеге"
    weight = 3
    url = "https://t.me/devlead"
[[menu.main]]
    name = "Чатик"
    weight = 4
    url = "https://t.me/arch_pain"