theme = "tech"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
defaultContentLanguage = "en"
baseURL = "https://antgubarev.tech"

[languages]

  [languages.en]
    title = 'Anton Gubarev'
	 contentDir = "content/en"
    weight = 1

  [languages.en.menu]

	  [[languages.en.menu.main]]
		 identifier = "github"
		 name = "github"
		 title = "github"
		 url = "https://github.com/antgubarev"
		 weight = 10
	   
	  [[languages.en.menu.main]]
		 identifier = "linkedin"
		 name = "linkedin"
		 title = "github"
		 url = "https://www.linkedin.com/in/antgubarev/"
		 weight = 20

	  [[languages.ru.menu.main]]
		identifier = "cv"
		name = "CV"
		title = "cv"
		url = "https://drive.google.com/file/d/1O2KRaw0AKy5mDJxwVaWim1jpYyj9LeVo/view?usp=sharing"
		weight = 30
		[languages.ru.menu.main.params]
			target = "_blank"

	  [[languages.en.menu.main]]
		 identifier = "ru"
		 name = "ru"
		 title = "ru"
		 url = "/ru/"
		 weight = 40

  [languages.ru]
    title = 'Anton Gubarev'
	contentDir = "content/ru"
    weight = 2

  [languages.ru.menu]
	  
	  [[languages.ru.menu.main]]
		identifier = "posts"
		name = "посты"
		title = "Посты"
		url = "/ru/posts/"
		weight = 1

	  [[languages.ru.menu.main]]
		identifier = "github"
		name = "github"
		title = "github"
		url = "https://github.com/antgubarev"
		weight = 10
		[languages.ru.menu.main.params]
			target = "_blank"
	   
	  [[languages.ru.menu.main]]
		identifier = "linkedin"
		name = "linkedin"
		title = "github"
		url = "https://www.linkedin.com/in/antgubarev/"
		weight = 20
		[languages.ru.menu.main.params]
			target = "_blank"

	  [[languages.ru.menu.main]]
		identifier = "cv"
		name = "CV"
		title = "cv"
		url = "https://drive.google.com/file/d/1O2KRaw0AKy5mDJxwVaWim1jpYyj9LeVo/view?usp=sharing"
		weight = 30
		[languages.ru.menu.main.params]
			target = "_blank"

	  [[languages.ru.menu.main]]
		 identifier = "en"
		 name = "en"
		 title = "en"
		 url = "/"
		 weight = 40

[params]
  description = "Anton Gubarev's personal website"
  copyright = "Copyright © 2023 Anton Gubarev"
  dark = "auto"
  highlight = true
  ymCode = "92567493"

[permalinks]
  posts = "/:year/:month/:slug/"

[markup.goldmark.renderer]
  unsafe = true
