name: Deploy to pages 

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: 
          - ls -labels:
          - tree
          - hugo --gc --minify --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
          cname: antgubarev.tech
          publish_branch: gh-pages
          publish_dir: ./public
          keep_files: true
